SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SHOT_RADIUS = 5
SHOOT_BAR_MAX = 200.0
SHOOT_BAR_FILL_RATE = 40.0
SHOOT_BAR_COOLDOWN_RATE = 15.0
SHOOT_BAR_RECOVERY_FRACTION = 0.5

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.1

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
    
LINE_WIDTH = 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


