SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SHOT_RADIUS = 5
SHOOT_BAR_MAX = 200.0
SHOOT_BAR_FILL_RATE = 40.0
SHOOT_BAR_COOLDOWN_RATE = 15.0
SHOOT_BAR_RECOVERY_FRACTION = 0.5

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.1

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
    
LINE_WIDTH = 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ENEMY_SPAWN_RATE_SECONDS = 2.0
ENEMY_SPEED = 120
ENEMY_SHOOT_SPEED = 400
ENEMY_SHOOT_COOLDOWN_SECONDS = 1.2
ENEMY_TURN_SPEED = 100
ENEMY_RADIUS = 18

# Waves
WAVE_ANNOUNCE_SECONDS = 2.0
WAVE_BASE_ASTEROIDS = 5
WAVE_ASTEROIDS_PER_LEVEL = 2
WAVE_BASE_SPAWN_INTERVAL = 0.7
WAVE_MIN_SPAWN_INTERVAL = 0.25
WAVE_SHIP_UNLOCK = 4  # enemy ships start appearing at this wave
WAVE_BASE_SHIPS = 1
WAVE_SHIPS_PER_LEVEL = 1



